### PR TITLE
Update i_have_no_idea_what_im_doing_help.md

### PR DESCRIPTION
**Pull request by sbaumohl**
This is my edit with the student discount added.

### CODE REVIEW

**Comment by michaelgira23** [comment]
Thanks for doing this! Could you fix these few things:
1. The first "github" isn't capitalized like the rest
2. Add a link to the [Git/GitHub guide](https://github.com/MICDS-Programming-Club/Programming-Club-Guides/blob/master/introduction/how_to_git_good.md) in the "What is GitHub?" section
3. Add a link to the page for the [GitHub Student Pack](https://education.github.com/pack)

**Review by michaelgira23 — CHANGES_REQUESTED** [review]
Just do those three things and we should be good to go for merging

**Comment by sbaumohl** [comment]
Added more stuff, hope you like it!

**Review by michaelgira23 — APPROVED** [review]

**Comment by michaelgira23** [comment]
Thanks for your contribution!

**Pull request merged**
